config/routes.rb
Rails.application.routes.draw do
  resources :clientes

  get 'stimulus', to: 'spa#index'
  root 'home#index'

  get 'fornecedores', to: 'fornecedores#index'
  get 'fornecedores/novo', to: 'fornecedores#novo', as: 'fornecedores_novo'

  post 'fornecedores', to: 'fornecedores#cadastrar', as: 'fornecedores_cadastrar'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    # paginação na maão sem gem
    page = params[:pagina].to_i || 1
    page = 1 if page < 1

    quantidade_por_pagina = 5

    offset = (page-1) * quantidade_por_pagina

    @clientes = Cliente.order(id: :desc).limit(quantidade_por_pagina).offset(offset)
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :telefone, :endereco)
    end
end

app/controllers/fornecedores_controller.rb
class FornecedoresController < ApplicationController
  def index
   @fornecedores = Fornecedor.all
   @fornecedores = Fornecedor.limit(4).order(id: "desc")
  end

  def novo
  end

  def cadastrar
    fornecedor = Fornecedor.new(parametros_de_fornecedor)
    if fornecedor.save
      flash[:notice] = "Cadastrado com sucesso"
      redirect_to fornecedores_path
    else
      flash[:error] = "Erro ao Cadastrar"
      render "novo"
    end
  end

  private

  def parametros_de_fornecedor 
    params.require(:fornecedor).permit(:nome, :razao_social, :cnpj, :endereco)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index;end
end

app/controllers/spa_controller.rb
class SpaController < ApplicationController
  def index;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Nome:</strong>
    <%= cliente.nome %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= cliente.telefone %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= cliente.endereco %>
  </p>

</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <a href="/">Voltar para Home</a><br>
    <h1>Editing cliente</h1>

    <%= render "form", cliente: @cliente %>

    <br>

    <div>
      <%= link_to "Show this cliente", @cliente %> |
      <%= link_to "Back to clientes", clientes_path %>
    </div>

  </div>
  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>

app/views/clientes/index.html.erb
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <a href="/">Voltar para Home</a><br>
    <h1>Clientes</h1>
    <hr style="margin: 0px;">

    <table>
      <thead>
        <% @clientes.each do |cliente| %>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Telefone</th>
          <th>Endereço</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= cliente.id %></td>
          <td><%= cliente.nome %></td>
          <td><%= cliente.telefone %></td>
          <td><%= cliente.endereco %></td>
          <td>
            <%= link_to "Mostrar", cliente %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Novo Cliente", new_cliente_path %>
  </div>

  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>

</section>

app/views/clientes/new.html.erb
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <a href="/">Voltar para Home</a><br>
    <h1>New cliente</h1>

    <%= render "form", cliente: @cliente %>

    <br>

    <div>
      <%= link_to "Back to clientes", clientes_path %>
    </div>

  </div>
  <div class="image filtered span-1-75" data-position="25% 25%">
      <img src="/images/pic01.jpg" alt="" />
    </div>
</section>

app/views/clientes/show.html.erb
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <a href="/">Voltar para Home</a><br>

    <p class="notice"><%= notice %></p>

    <%= render @cliente %>

    <div>
      <%= link_to "Edit this cliente", edit_cliente_path(@cliente) %> |
      <%= link_to "Back to clientes", clientes_path %>

      <%= button_to "Destroy this cliente", @cliente, method: :delete %>
    </div>


  </div>
  <div class="image filtered span-1-75" data-position="25% 25%">
      <img src="/images/pic01.jpg" alt="" />
    </div>
</section>

app/views/fornecedores/index.html.erb
<section class="panel banner right">
  <div class="content color0">
    <a href="/">Voltar para Home</a><br>
    <h1>Fornecedores</h1>

    <%= link_to "Novo Fornecedor", fornecedores_novo_path %>
    <!-- <a href="<%=fornecedores_novo_path %>">Novo Fornecedor</a> -->

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Razão Social</th>
                <th>CNPJ</th>
                <th>Endereço</th>
            </tr>
        </thead>
        <tbody>
          <% @fornecedores.each do |fornecedor| %>
            <tr>
              <td><%= fornecedor.id %></td>
              <td><%= fornecedor.nome %></td>
              <td><%= fornecedor.razao_social %></td>
              <td><%= fornecedor.cnpj %></td>
              <td><%= fornecedor.endereco %></td>
              <td>
            </tr>
          <% end %>
        </tbody>
    </table>

  </div>

  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>
 

app/views/fornecedores/novo.html.erb
<section class="panel banner right">
  <div class="content color0">
    <a href="/">Voltar para Home</a><br>
    <h1>Novo Fornecedor</h1>

    <a href="<%= fornecedores_path%>">Lista de Fornecedores</a>
    <form action="<%= fornecedores_cadastrar_path %>" method="post">
      <label for="nome">Nome:</label>
      <input type="text" id="nome" name="fornecedor[nome]" required>
      
      <label for="razao_social">Razão Social:</label>
      <input type="text" id="razao_social" name="fornecedor[razao_social]" required>
    
      <label for="cnpj">CNPJ:</label>
      <input type="text" id="cnpj" name="fornecedor[cnpj]" required>
      
      <label for="endereco">Endereço:</label>
      <input type="text" id="endereco" name="fornecedor[endereco]" required>
      <br>
      <input type="submit" value="Cadastrar">
    </form>

  </div>

  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>

app/views/home/index.html.erb
<!-- Panel (Banner) -->
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <h1 class="major">Desafio Rails Avançado<br /></h1>
    <p>Essencial Software</p>
    <ul class="actions">
      <li><a href="#first" class="button primary color1 circle icon solid fa-angle-right">Next</a></li>
    </ul>
  </div>
  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>
<!-- Panel (Spotlight) -->
<section class="panel spotlight medium right" id="first">
  <div class="content span-7">
    <h2 class="major">Cadastro de clientes</h2>
    <p>
      Cadastro de clientes gerado pelo scaffold
    </p>
    <a href="/clientes">Clique aqui para acessar</a>
  </div>
  <div class="image filtered tinted" data-position="top left">
    <img src="/images/pic02.jpg" alt="" />
  </div>
</section>

<section class="panel color1">
  <div class="intro joined">
    <h2 class="major">Stimulus</h2>
    <p>
     o Stimulus não pretende assumir o controle do front-end de uma aplicação e
     <br>
    apesar de não depender, combinado com Turbolinks,
    <br>
    fornece uma solução completa para aplicativos rápidos e
    <br> 
    convincentes com uma quantidade mínima de esforço.
    <br>
    </p>
  </div>
  <div class="inner">
    <ul class="grid-icons three connected">
      <li><span class="icon fa-gem"><span class="label">Lorem</span></span></li>
      <li><span class="icon solid fa-camera-retro"><span class="label">Ipsum</span></span></li>
      <li><span class="icon solid fa-cog"><span class="label">Dolor</span></span></li>
      <li><span class="icon solid fa-paper-plane"><span class="label">Sit</span></span></li>
      <li><span class="icon solid fa-chart-bar"><span class="label">Amet</span></span></li>
      <li><span class="icon solid fa-code"><span class="label">Nullam</span></span></li>
    </ul>
    <br>
    <a href="/stimulus"><h3>Clique aqui e veja um exemplo</h3>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title>Treinamento rails avançado</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="/assets/css/main.css" />
    <noscript>
      <link rel="stylesheet" href="/assets/css/noscript.css" />
    </noscript>
  </head>
  <body>
    <div id="page-wrapper">
      <div id="wrapper">
        <% if notice.present? %>
          <p class="notice"><%= notice %></p>
        <% end %>

        <% if flash[:error].present? %>
          <p class="error"><%= flash[:error] %></p>
        <% end %>

        <%= yield %>
      </div>
    </div>

    <div class="copyright" style="color: #000;min-width: 500px;padding: 30px;">
      &copy; Untitled. Design: <br> 
      &nbsp;&nbsp;&nbsp;&nbsp; <a href="https://html5up.net">HTML5 UP</a>.<br><br>
      &copy; Essencial software. Rails avançado: <br>
      &nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.linkedin.com/in/daniel-candido-8b8724bb/">Acessar</a>.
    </div>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/browser.min.js"></script>
    <script src="/assets/js/breakpoints.min.js"></script>
    <script src="/assets/js/main.js"></script>
  </body>
</html>

app/views/spa/index.html.erb
<!-- Panel (Banner) -->
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <a href="/">Voltar para Home</a><br>
    <br>
    <br>
    <div data-controller="hello">
        Meu codigo ...
    </div>
   </div>

  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>